spring.application.name=user-serviceSpring


#<property name="hibernate.connection.url">jdbc:postgresql://localhost:5432/userdb</property>
#<property name="hibernate.connection.username">admin</property>
#<property name="hibernate.connection.password">admin</property>


spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

